name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [16]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          depth: 1

      - name: Set up Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm install
          npm run all

  test: # make sure the action works on a clean machine without building
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          depth: 1

      - uses: ./
        id: secretize
        name: 'secretize test'
        with:
          string: 'app_name'

      - name: 'result'
        if: steps.secretize.outputs.return == 'APP_NAME'
        run: exit 0

